### ISSUE TITLE
Revert commit 17106d8f

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-spamprotection#103]
That commit makes a bunch of changes that skipped the peer review process, which definitely need to be talked about before they're made:

- Change `code/` to `src/`
- add allow-plugins (which shouldn't be added to modules)
- change an intentional exception to a console error, which is arguably a breaking change but at least a change to the intent of the module.

When upgrading the module to CMS 5 compatability we made an intentional decision not to change or remove this exception, since a missing spam protection module is a clear example of missing dependencies that a developer needs to be aware of early on. If there's no spam protection module utilising this one, then this module should not be installed on that project.

## PR
- https://github.com/silverstripe/silverstripe-spamprotection/pull/104

**Comment by GuySartorelli** [comment]
FYI @wilr - after it has been reverted, feel free to submit a pull request so that the correct peer review process can take place.

**Comment by GuySartorelli** [comment]
The linked PR was merged

**Comment by wilr** [comment]
@GuySartorelli New PR for you to add any comments too at https://github.com/silverstripe/silverstripe-spamprotection/pull/105
