### ISSUE TITLE
spamprotection "white screen of death"?!?

### ISSUE THREAD

**Issue by mhenden** [silverstripe/silverstripe-spamprotection#15]
This module has great promise -- I _REALLY_ _HATE_ _SPAM_ -- but I think I'm doing something wrong? Have loaded "spamprotection" and "recaptcha" directories in site root directory and dev/build/ as well as ?flush=1 and ?flush=all (nothing actually seemed to happen), then opened ContactForm.php and, within the public function _construct string I added the following: 

```
$recaptchaField = new RecaptchaField('MyCaptcha');
$recaptchaField->jsOptions = array('theme' => 'clean'); // optional
```

So far so good. It's when I include:

```
   $form->enableSpamProtection();
```

and flush again that I get the white screen of death. 

Am I placing this code in the right place? I don't think so!

**Comment by robbieaverill** [comment]
Closing, originally reported issue was due to incorrect implementation and the issue has had no feedback in three years.

If anyone is still having issues with this please open a new issue which correctly identifies the new problem =)
