### ISSUE TITLE
added editablespamprotectionfield to userform, but it does not appear

### ISSUE THREAD

**Issue by Lukin** [silverstripe/silverstripe-spamprotection#21]
hi I added the field in the formconfiguration of userforms, but the field does not appear...
All fields of my form that are under the spmaprotectionfield disappear too...
## name: spamprotection

FormSpamProtectionExtension:
  default_spam_protector: MollomSpamProtectors
Mollom:
  public_key: 58ffee9caeb0d4689772fc97f43e6872
  private_key: 479f040d67dafc0eb3b9545234e2fc71
## name: spamprotection

Form:
  extensions:
    - FormSpamProtectionExtension

**Comment by wilr** [comment]
Hi @Lukin, make sure your site is in dev mode so you see any errors and double check the name of the protector. Should be MollomSpamProtector not Protectors

**Comment by Lukin** [comment]
Hi @wilr , thanks. Now I'm getting that white screen of death ;) Any advice?

**Comment by Lukin** [comment]
I had to add the file /vendor/mollom/client/mollom.class.inc,... one step forward: now the foloowing markup is appended, but no still no protection:

<div class="field mollom nolabel" id="EditableSpamProtectionField29">	
	<div class="middleColumn">		
	
	<input type="hidden" value="" name="EditableSpamProtectionField29"></div>
	<label for="Form_Form_EditableSpamProtectionField29" class="right">Spamprotection</label>	
</div>

**Comment by dhensby** [comment]
@Lukin Mollom fields will only show if the submission looks spammy, it shouldn't be present constantly.

Also, it won't show for logged in users (or ADMINs at least) so if you're logged into the CMS, don't expect to see it either.

**Comment by Lukin** [comment]
hej, ok thanks.
so is there a way to test it?

**Comment by dhensby** [comment]
Enter spammy content into the submission? Swear-words, particular drug names, etc..

**Comment by dhensby** [comment]
Oh, and log out when you test

**Comment by robbieaverill** [comment]
Actually I'm going to close this as it sounds more like a question than a bug report. @Lukin you'd be welcome to ask for further assistance (if you still need it, which you probably don't!) via Stackoverflow, SilverStripe Forums or the SS community Slack channel.
