### ISSUE TITLE
EditableSpamProtectionField  error message is not helpful 

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-spamprotection#39]
A few things have broken with the introduction of UserForms 3 and matching SpamProtection 2.0.2 (people will still not know that dependency). 

I have managed to suggest fixes for a few of the popular Spam modules which were broken (due to a mysterious object break that I have not yet figured out) but there is also a remaining issue. Clearly UserForms largely does its error checking and validation in Javascript but when one is using a Spam Protection module, even one such as SpamProtection Honeypot,  one needs an erorr message returned which is meaningful and not just "EditableFieldxxx is required". This is uninformative and whilst one can tweak the name, it is still poor.

Around line 110 of EditableSpamProtectionField.php I have changed to code from:

$form->addErrorMessage($this->Name, $this->getErrorMessage()->HTML(), 'error', false);

to

$form->addErrorMessage($this->Name, 'Incorrect Spam Validation', 'error', false);

This is clearly an awful modification right now. It would be far better to return the output of my Captch test:

```
    if(Controller::curr()->getRequest()->postVar($this->getName())) {
        $validator->validationError(
            $this->name, 
            _t(
                'SimpleSpamProtector.INCORRECTCAPTCHA', 
                "You didn't type in the correct captcha text. Please try again."
            ), 
            "validation", 
            false
        );
        return false;
    }
```

But as yet I have not figured out how, sorry

**Comment by tazzydemon** [comment]
And here it is with an included function if you are on PHP5.4 or below. I only had an array of 1 to work with here - my own spam checker

EditableSpamProtectionField.php:

		public function validateField($data, $form) {
			$formField = $this->getFormField();
            if(!function_exists("array_column")){
                function array_column($array,$column_name){
                    return array_map(function($element) use($column_name){return $element[$column_name];}, $array);
                   }
            }
			if (!$formField->validate($form->getValidator())) {

                $errorArray = $form->getValidator()->getErrors();
                $errorText = $errorArray[array_search($this->Name, array_column($errorArray, 'fieldName'))]['message'];
                $form->addErrorMessage($this->Name, $errorText, 'error', false);
				//$form->addErrorMessage($this->Name, $this->getErrorMessage()->HTML(), 'error', false);
			}
		}

**Comment by tazzydemon** [comment]
It looks like the getErrors array depth is never greater than 1 as we get a new instance for each iteration of validateField and not all of them. I tested this with two named spamprotection fields and only ever got one array each time: 

array (size=1)
  0 => 
    array (size=3)
      'fieldName' => string 'SpamprotectionOne' (length=17)
      'message' => string 'You didn't type in the correct captcha text. Please try again.SpamprotectionOne' (length=79)
      'messageType' => string 'validation' (length=10)

This means the previous entry could be simplified by removing the array_column stuff to:

		public function validateField($data, $form) {
					$formField = $this->getFormField();

					if (!$formField->validate($form->getValidator())) {
		                $errorArray = $form->getValidator()->getErrors();
		                $errorText = $errorArray[0]['message'];
		                $form->addErrorMessage($this->Name, $errorText, 'error', false);
						//$form->addErrorMessage($this->Name, $this->getErrorMessage()->HTML(), 'error', false);
					}
				}

YMMV!! Enjoy.

**Comment by tractorcow** [comment]
This may have been fixed with https://github.com/silverstripe/silverstripe-userforms/pull/409

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
