### ISSUE TITLE
Conflicts with other javascript on the page

### ISSUE THREAD

**Issue by cmcramer** [silverstripe/silverstripe-spamprotection#45]
I have a jquery script which runs a slideshow below a UserDefinedForm. It works correctly until I add a SpamProtectionField on the form. My script is wrapped in jquery No Conflict.

**Comment by tractorcow** [comment]
Do you get an error at all? what scripts are included on your page?

**Comment by cmcramer** [comment]
No errors. It may be related to how the javascript is being loaded. When there is no SpamProtection field the javascript is all loaded before the closing </body> tag. When a SpamProtection field is included, the javascript gets added in the <div class="middleColumn"> of the Captcha field.

**Comment by dhensby** [comment]
Which spam protector are you using?

**Comment by tractorcow** [comment]
Maybe if you show us your composer.json to help us check what version, too.

**Comment by cmcramer** [comment]
I'm using Recaptcha. This is my composer require for spamprotection:

```"silverstripe/spamprotection": "*",```

**Comment by tractorcow** [comment]
Oh, I do recall the JS for recaptcha being a bit of an issue. I haven't used it for quite a while though.

What scripts are loaded in your request in what order? Maybe the order is wrong when including the recaptcha field.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
