### ISSUE TITLE
Cannot configure on User Forms 3.x/4.x 

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-spamprotection#47]
This field cannot be configured anymore as User Forms 3.x/4.x is not backwards compatible with 'getFieldConfiguration' function.

**Comment by tractorcow** [comment]
It looks like the fix would be to:

- Rename getFieldConfiguration() to getCMSFields()
- Fix deprecated usage of get/setSetting (probably by adding another DB field to EditableSpamProtectionField)
- Update getFormField() to use new DB field for mapping fields to spam tags.

**Comment by SilbinaryWolf** [comment]
Not really. For me this is more of a 'flagging the problem' as I don't personally need to configure anything and I just use it 'as-is'.

Already updated another module here and it's fairly trivial:
https://github.com/sheadawson/silverstripe-dynamiclists/commit/d2ab3c241219348e31d26cb4c9e52ccb9f1d6f5f

But it might be worth making UDF 3.x/4.x 'just work' with the older stuff incase people have in-house modules that broke in the transition.

**Comment by camfindlay** [comment]
Take it this is still an issue? I'm finding trouble with getting Akismet spam protector to work as expected with user defined forms for the latest (1.6.0) CWP bundle versions. I'm happy to have a crack at a fix here if you have any further guidance on this @tractorcow ?
