### ISSUE TITLE
Uncaught Exception: Object->__call(): the method 'enablespamprotection' does not exist on 'Form'

### ISSUE THREAD

**Issue by fp-ke** [silverstripe/silverstripe-spamprotection#49]
I have ss3.4.0 and comments (master) and I use captcha. Everthing works fine with user forms but there is no way I can get the spam protection in my comments form in the blog module. I tried every configration I found and either nothing changes or I get this error:

[User Error] Uncaught Exception: Object->__call(): the method 'enablespamprotection' does not exist on 'Form'

What do I do wrong?

**Comment by tractorcow** [comment]
That's quite odd... all forms should have the FormSpamProtectionExtension extension applied which provides the enableSpamProtection method.

Is there anything else in the stack trace that might show where the error came up?

**Comment by fp-ke** [comment]
Sorry for the late response, I was on business travel.

I now tried it with a simple form from the tutorials, same result. Here's the trace:

`Object->__call(enableSpamProtection,Array) 
TestPage.php:28
Form->enableSpamProtection() 
TestPage.php:28
TestPage_Controller->HelloForm() 
ViewableData.php:446
ViewableData->obj(HelloForm,,,1) 
ViewableData.php:519
ViewableData->XML_val(HelloForm,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:187
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:643
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.themes.lernspirale.templates.Layout.TestPage.ss:13
SSViewer_DataPresenter->XML_val(HelloForm,,1) 
.cache.themes.lernspirale.templates.Layout.TestPage.ss:13
include(.xxxx.silverstripe-cache\WL38\.cache.themes.xxxx.templates.Layout.TestPage.ss) 
SSViewer.php:1157
SSViewer->includeGeneratedTemplate(.xxxx.silverstripe-cache\WL38/.cache.themes.xxxx.templates.Layout.TestPage.ss,TestPage_Controller,,Array,) 
SSViewer.php:1219
SSViewer->process(TestPage_Controller,) 
SSViewer.php:1215
SSViewer->process(TestPage_Controller) 
Controller.php:211
Controller->handleAction(SS_HTTPRequest,index) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
ContentController.php:174
ContentController->handleRequest(SS_HTTPRequest,DataModel) 
ModelAsController.php:75
ModelAsController->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:385
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:149
Director::direct(neue-test,DataModel) 
main.php:188`

**Comment by tractorcow** [comment]
You aren't on an old spam protector version are you?

You should have https://github.com/silverstripe/silverstripe-spamprotection/blob/master/_config/spamprotection.yml to setup the extension against Form, which applies this extension to it https://github.com/silverstripe/silverstripe-spamprotection/blob/master/code/extensions/FormSpamProtectionExtension.php

If both those files are in place, I'll need to look deeper. :)

**Comment by fp-ke** [comment]
It's working. I guess the two files

mysite/_config/spamprotection.yml
spamprotection/_config/spamprotection.yml

got mixed up. My fault. Sorry for bothering you and thanks a lot for your help.

**Comment by tractorcow** [comment]
If I managed to help you it's not a bother. :)
