### ISSUE TITLE
Add css class into spamprotection field using UserDefinedForm

### ISSUE THREAD

**Issue by intwebg** [silverstripe/silverstripe-spamprotection#61]
Hi! Adding css classes to UserDefinedForm spamprotection field doesnt work. I'm using bootstrap grid to align my elements but spamprotection field dont display the css class on frontend.

**Comment by robbieaverill** [comment]
Can you please enable `SSViewer.source_file_comments: true` in your configuration and provide the template name that your field is using?

**Comment by robbieaverill** [comment]
@intwebg please feel free to reopen this issue with some supporting information - thanks for reporting!

**Comment by intwebg** [comment]
No error when using SSViewer.source_file_comments:true

But check this html code example bellow : 


```
<div id="EditableTextField_2301c" class="field text col-sm-3">
<label class="left" for="UserForm_Form_EditableTextField_2301c">Name</label>
<div class="middleColumn">
<input type="text" name="EditableTextField_2301c" class="text col-sm-3" id="UserForm_Form_EditableTextField_2301c" autocomplete="off"/>
</div>
 </div>
 
<div id="EditableTextField_70bc5" class="field email text col-sm-3">
<label class="left" for="UserForm_Form_EditableTextField_70bc5">Email</label>
<div class="middleColumn">
<input type="email" name="EditableTextField_70bc5" class="email text col-sm-3" id="UserForm_Form_EditableTextField_70bc5" data-rule-email="data-rule-email"/>
</div>
</div>
   
<div id="UserForm_Form_EditableTextField_28fec_Holder" class="field recaptcha">
<label class="left" for="UserForm_Form_EditableTextField_28fec">Spam protection</label>
<div class="middleColumn">
<div class="g-recaptcha" id="EditableTextField_28fec" data-sitekey="6LeHajsUAAAAACxRG-v8OhbC1r6zBiferGlzodnr" ></div>
</div>
```

Above there are 3 fields. Only on my email and name field are added col-sm-3 class. The class is missing next to recaptcha class. It must show as :  

```
<div id="UserForm_Form_EditableTextField_28fec_Holder" class="field recaptcha col-sm-3">
<label class="left" for="UserForm_Form_EditableTextField_28fec">Spam protection</label>
<div class="middleColumn">
<div class="g-recaptcha" id="EditableTextField_28fec" data-sitekey="6LeHajsUAAAAACxRG-v8OhbC1r6zBiferGlzodnr" ></div>
</div>
```

**Comment by robbieaverill** [comment]
Thanks for that @intwebg. Can you please provide the UserForms version, and the version of this module you're using?

**Comment by intwebg** [comment]
there is the report : 

ajshort/silverstripe-gridfieldextensions  1.1.0   A collection of useful gr...
composer/installers                       v1.4.0  A multi-framework Compose...
mustangostang/spyc                        0.6.2   A simple YAML loader/dump...
phpunit/php-code-coverage                 1.2.18  Library that provides col...
phpunit/php-file-iterator                 1.4.5   FilterIterator implementa...
phpunit/php-text-template                 1.2.1   Simple template engine.
phpunit/php-timer                         1.0.9   Utility class for timing
phpunit/php-token-stream                  1.2.2   Wrapper around PHP's toke...
phpunit/phpunit                           3.7.38  The PHP Unit Testing fram...
phpunit/phpunit-mock-objects              1.2.3   Mock Object library for P...
silverstripe-themes/simple                3.1.0   The SilverStripe simple t...
silverstripe/cms                          3.6.2   The SilverStripe Content ...
silverstripe/framework                    3.6.2   The SilverStripe framework
silverstripe/recaptcha                    2.0.1   Provides a form field whi...
silverstripe/reports                      3.6.2   Reports module for Silver...
silverstripe/segment-field                1.0.3   A reusable approach to se...
silverstripe/siteconfig                   3.6.2   Site wide settings admini...
silverstripe/spamprotection               2.0.8   Spam protection module fo...
silverstripe/userforms                    4.5.4   UserForms enables CMS use...
symbiote/silverstripe-gridfieldextensions 2.0.1   A collection of useful gr...
symfony/yaml                              v2.8.31 Symfony Yaml Component

**Comment by robbieaverill** [comment]
Thank you!

**Comment by maxime-rainville** [comment]
I think this still affect SS4.

**Comment by emteknetnz** [comment]
The linked PR has been merged, I'll close this issue now
