### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-spamprotection#62]
## Acceptance Criteria

- [x] Works on SS4
- [x] Translations are updated
- [x] Transifex is removed from SS3 branches
- [x] Transifex is updated
- [x] Beta tag released

**Comment by raissanorth** [comment]
Note: can use https://github.com/silverstripe/silverstripe-akismet to test this module with as well

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-spamprotection/releases/tag/3.0.0-beta1

Nice work @raissanorth!
