### ISSUE TITLE
[Question] Multiple Spam Protectors

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-spamprotection#72]
Hello!

I'm working on a project that wants different forms of spam protection for different forms. Would it be possible for me to use something like Akismet on certain forms, and reCaptcha on others? I only see documentation for one, but maybe it's possible.

Thanks!

**Comment by NightJar** [comment]
Hi Bryce,

Calling `enableSpamProtection(['protector' => $protector])` will alter the form with the protector specified - allowing individual form customisation as to what protector is used.
